### ISSUE TITLE
Snake

### ISSUE THREAD

**Issue by ApolllonDev** [ApolllonDev/Python-Projects#1]
## **TODO**
- [ ] self_collision check
- [ ] add more comments
- [ ] make sure the snake doesn't move as game is over
- [ ] game_over() -> move to the Game class
- [ ] check why onkey() doesn't work with while/recursion 
- [ ] food won't appear on the snake itself
- [ ] add border to the game
- [ ] add Start and Game over Scene

**Comment by ApolllonDev** [comment]
Testing the issue
